### ISSUE TITLE
For NaverBoostCamp image upload

### ISSUE THREAD

**Issue by ParkSeongGeun** [ParkSeongGeun/ParkSeongGeun#1]
![상태관리다이어그램](https://github.com/ParkSeongGeun/ParkSeongGeun/assets/117553364/c40a871e-2931-4671-824f-5c7d1d3fdd6b)

**Comment by MinboyKim** [comment]
재밌어보이네요

**Comment by ParkSeongGeun** [comment]
<img width="316" alt="스크린샷 2024-07-16 오후 4 48 05" src="https://github.com/user-attachments/assets/f9a3a01d-19ff-42c4-8404-716d977bd77a">
<img width="455" alt="스크린샷 2024-07-16 오후 4 41 40" src="https://github.com/user-attachments/assets/fd48c3d5-8490-4610-8772-2aecd8057251">
<img width="482" alt="스크린샷 2024-07-16 오후 4 38 07" src="https://github.com/user-attachments/assets/96dc232c-52fa-484d-9583-cc86fa371213">
<img width="607" alt="스크린샷 2024-07-16 오후 4 34 05" src="https://github.com/user-attachments/assets/ba968d77-9b17-4afa-9f9d-1f1d5e470e26">
<img width="757" alt="스크린샷 2024-07-16 오후 4 09 22" src="https://github.com/user-attachments/assets/8200a7a1-7caf-4ca8-8668-312065bed06d">
<img width="490" alt="스크린샷 2024-07-16 오후 4 06 32" src="https://github.com/user-attachments/assets/160374a5-1b51-4a78-9000-fb796d053771">

**Comment by ParkSeongGeun** [comment]
<img width="529" alt="image" src="https://github.com/user-attachments/assets/42b6ddd6-dca1-4491-bfde-743f8db2c6cd">
